# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expericence',
            new_name='Experience',
        ),
    ]
