# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_auto_20160612_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='classes',
            field=models.CharField(default='fa', max_length=100),
            preserve_default=False,
        ),
    ]
